# Generated by Django 5.1.3 on 2024-11-30 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 8, 9, 30, 246218, tzinfo=datetime.timezone.utc)),
        ),
    ]
