# Generated by Django 5.1.3 on 2024-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_due_date_alter_todo_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
